export const Constant = {
    BASE_URI : 'https://localhost:7194/api/',   //ayush uri
    // BASE_URI : 'https://localhost:7101/api/', //khushi uri
    LOGIN:'Authentication/login',
    REGISTER:'Authentication/register',
    LOGOUT: 'Authentication/logout',
    GetAllBuses: 'Bus/GetAllBuses',
    GetSeatsByBusId: 'Bus/GetSeatsByBusId/',
    GetScheduledSeatsByScheduleId: 'Bus/GetScheduledSeatsByScheduleId/',
    SearchBuses: 'Booking/SearchBus/',
    GetUserById: 'Users/GetUserById/',
    UpdateUser: 'Users/UpdateUser/',
    DeleteUser: 'Users/DeleteUser/',
    ReactivateUser: 'Users/reactivate/',
    GetScheduleById: 'Schedule/GetScheduleById/',
    GetBusById: 'Bus/GetBusById/',
    BookTicket: 'Booking/BookTicket',
    UpdatePayment: 'Payment/InitiatePayment',
    CancelBooking: 'Booking/CancelBooking',
    BookingsByUserId: 'Booking/ViewBookingsByUserId/',
    BookingByBookingId: 'Booking/ViewBookingByBookingId/',
    UpdatePaymentToRefund: 'Payment/InitiateRefund',
    PaymentStatus: 'Payment/GetPaymentStatus/',
    CreateRoute: 'Route/CreateRoute',
    ViewAllRoutes: 'Route/GetAllRoutes',
    UpdateRoute: 'Route/UpdateRoute/',
    DeleteRoute: 'Route/DeleteRoute/',
    CreateBus: 'Bus/CreateBus',
    DeleteBus: 'Bus/DeleteBus/',
    ViewSeatLogs: 'Booking/GetSeatLogByBookingId/',
    GetBusesByOperatorId: 'Bus/GetBusesByOperatorId/',
    UpdateBus: 'Bus/UpdateBus/',
    GetAllSchedules: 'Schedule/GetAllSchedules',
    GetSchedulesByBusId: 'Schedule/bus/',
    GetSchedulesByOperatorId: 'Schedule/GetSchedulesByOperatorId/',
    GetOperatorByBusId: 'Bus/GetOperatorByBusId/',
    CreateSchedule: 'Schedule/CreateSchedule',
    UpdateSchedule: 'Schedule/UpdateSchedule/',
    DeleteSchedule: 'Schedule/DeleteSchedule/',
    GenerateReports: 'AdminDashboard/GenerateReports',
    FetchAllUsers: 'Users/GetAllUsers',
    SendNotification: 'Notification/SendNotification',
    ViewNotification: 'Notification/ViewNotifications/',
    MarkNotificationAsRead: 'Notification/MarkNotificationAsRead/',
}